(lang dune 3.20)

(name ninety-nine-ocaml-problems)

(generate_opam_files true)

(source
 (github papayankey/ninety-nine-ocaml-problems))

(authors "Benneth Yankey <yankeybenneth@gmail.com>")

(maintainers "Benneth Yankey <yankeybenneth@gmail.com>")

(license LICENSE)

(package
 (name ninety-nine-ocaml-problems)
 (synopsis
  "A ninety-nine ocaml exercises inspired by ninety-nine lisp problems")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
